# Generated by Django 4.2.3 on 2023-07-11 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decenttralization', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('gmail', models.EmailField(max_length=300, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(max_length=300)),
                ('IDpermission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.permission')),
            ],
        ),
    ]
